/**
 * API types generated from the backend OpenAPI contract.
 *
 * This file is a placeholder. The real types are generated by:
 *
 *   npm run gen:api
 *
 * which runs `openapi-typescript ../api/openapi.json -o src/api/schema.ts`.
 * First produce the contract on the API side with:
 *
 *   python scripts/export_openapi.py   # writes apps/api/openapi.json
 *
 * Do not hand-edit the generated output; re-run `npm run gen:api` instead.
 */
export type Generated = never;
